// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import CalculatorController from "controllers/calculator_controller"
application.register("calculator", CalculatorController)

import CourseSettingsController from "controllers/course_settings_controller"
application.register("course-settings", CourseSettingsController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import NotificationsController from "controllers/notifications_controller"
application.register("notifications", NotificationsController)

import PasswordValidationController from "controllers/password_validation_controller"
application.register("password-validation", PasswordValidationController)

import PeerRatingController from "controllers/peer_rating_controller"
application.register("peer-rating", PeerRatingController)

import PointPoolController from "controllers/point_pool_controller"
application.register("point-pool", PointPoolController)

import RegistrationValidationController from "controllers/registration_validation_controller"
application.register("registration-validation", RegistrationValidationController)

import RubricEditorController from "controllers/rubric_editor_controller"
application.register("rubric-editor", RubricEditorController)

import RubricReviewController from "controllers/rubric_review_controller"
application.register("rubric-review", RubricReviewController)

import TabsController from "controllers/tabs_controller"
application.register("tabs", TabsController)

import DateValidationController from "controllers/date_validation_controller"
application.register("date-validation", DateValidationController)

import MarkdownEditorController from "controllers/markdown_editor_controller"
application.register("markdown-editor", MarkdownEditorController)
